#!/usr/bin/env bash
set -eu

function package-lambda() {
  local -r project="$1"

  echo 1>&2
  pushd "$project"
    build "$project" dist/package
    create-package
  popd
}

function package-layer() {
  local -r project="$1"

  echo 1>&2
  pushd "$project"
    build "$project" dist/package/python
    create-package
  popd
}

function build() {
  local -r project="$1"
  local -r target="$2"

  rm -rf dist
  poetry install --sync
  poetry build --format=wheel
  poetry export --format=requirements.txt --output=dist/requirements.txt
  poetry run pip install --no-compile --target "$target" --requirement dist/requirements.txt
  unzip -q "dist/${project//-/_}-$(poetry version --short)-*.whl" -d "$target"
}

function create-package() {
  pushd dist/package
    zip -q -r ../bundle.zip . -x "bin/*"
  popd
}

function main() {
  package-layer http-lib
  package-lambda feature-toggles
}

main "$@"
