openapi: "3.0.1"

info:
  title: API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  "/toggles":
    get:
      summary: Returns the current toggle values for this account.
      responses:
        200:
          description: A JSON object mapping toggle names to values.
      x-amazon-apigateway-integration:
        uri: ${toggles-arn}
        type: aws_proxy
        httpMethod: POST
